class Internal_Error(Exception):
   pass